package config

import (
	"log"
	"os"
	"strconv"
	"strings"
	"time"
)

type Config struct {
	HTTPAddr       string
	DatabaseURL    string
	RedisAddr      string
	RedisPassword  string
	AllowedOrigins []string

	JWTSecret       string
	AccessTokenTTL  time.Duration
	RefreshTokenTTL time.Duration

	EncryptionKey string

	SourceDir string
	RepoSlug  string

	RequireAdmin2FA bool

	SMTPHost     string
	SMTPPort     string
	SMTPUsername string
	SMTPPassword string
	SMTPFrom     string

	// PublicURL is this panel's own publicly-reachable address (scheme +
	// host), e.g. https://panel.example.com. Written by the installer once
	// domain/TLS setup finishes. Needed for building OAuth redirect URIs
	// (Twitch, and anything else later) that outside services redirect the
	// user's browser back to — those can't be relative paths, since the
	// redirect happens from twitch.tv, not from this app.
	PublicURL string

	// Twitch OAuth app credentials. Unset by default -- the integration is
	// simply disabled until an admin registers an app at
	// dev.twitch.tv/console and sets these, same opt-in shape as the SMTP
	// settings above.
	TwitchClientID     string
	TwitchClientSecret string

	// TwitchEventSubSecret signs/verifies Twitch's EventSub webhook
	// deliveries (subscription alerts). Auto-generated by the installer
	// alongside the other secrets -- unlike the client ID/secret, this one
	// isn't something an admin registers anywhere, it's purely ours.
	TwitchEventSubSecret string

	// Stripe Connect powers donations: streamers connect their own Stripe
	// Express account (Stripe handles onboarding/KYC entirely, we never
	// touch it), viewers pay via a platform-created Checkout Session, funds
	// go straight to the streamer's account minus DonationPlatformFeeBps.
	// Unset by default -- same opt-in shape as Twitch/SMTP above. An admin
	// registers a Stripe account and pastes these in.
	StripeSecretKey        string
	StripeWebhookSecret    string
	DonationPlatformFeeBps int

	// Spotify song requests: same opt-in shape as Twitch/Stripe -- unset
	// disables the feature entirely rather than erroring.
	SpotifyClientID     string
	SpotifyClientSecret string
}

func Load() Config {
	cfg := Config{
		HTTPAddr:               getEnv("PANEL_HTTP_ADDR", ":8080"),
		DatabaseURL:            getEnv("PANEL_DATABASE_URL", "postgres://panel:panel@localhost:5432/panel?sslmode=disable"),
		RedisAddr:              getEnv("PANEL_REDIS_ADDR", "localhost:6379"),
		RedisPassword:          getEnv("PANEL_REDIS_PASSWORD", ""),
		AllowedOrigins:         splitCSV(getEnv("PANEL_ALLOWED_ORIGINS", "http://localhost:5173")),
		JWTSecret:              os.Getenv("PANEL_JWT_SECRET"),
		AccessTokenTTL:         15 * time.Minute,
		RefreshTokenTTL:        30 * 24 * time.Hour,
		EncryptionKey:          os.Getenv("PANEL_ENCRYPTION_KEY"),
		SourceDir:              getEnv("PANEL_SOURCE_DIR", ""),
		RepoSlug:               getEnv("PANEL_UPDATE_REPO", "superbodik/PowerNode"),
		RequireAdmin2FA:        getEnv("PANEL_REQUIRE_ADMIN_2FA", "false") == "true",
		SMTPHost:               getEnv("PANEL_SMTP_HOST", ""),
		SMTPPort:               getEnv("PANEL_SMTP_PORT", "587"),
		SMTPUsername:           getEnv("PANEL_SMTP_USERNAME", ""),
		SMTPPassword:           getEnv("PANEL_SMTP_PASSWORD", ""),
		SMTPFrom:               getEnv("PANEL_SMTP_FROM", ""),
		PublicURL:              strings.TrimSuffix(getEnv("PANEL_PUBLIC_URL", ""), "/"),
		TwitchClientID:         getEnv("PANEL_TWITCH_CLIENT_ID", ""),
		TwitchClientSecret:     getEnv("PANEL_TWITCH_CLIENT_SECRET", ""),
		TwitchEventSubSecret:   getEnv("PANEL_TWITCH_EVENTSUB_SECRET", ""),
		StripeSecretKey:        getEnv("PANEL_STRIPE_SECRET_KEY", ""),
		StripeWebhookSecret:    getEnv("PANEL_STRIPE_WEBHOOK_SECRET", ""),
		DonationPlatformFeeBps: parseIntEnv("PANEL_DONATION_FEE_BPS", 500), // 500bps = 5%
		SpotifyClientID:        getEnv("PANEL_SPOTIFY_CLIENT_ID", ""),
		SpotifyClientSecret:    getEnv("PANEL_SPOTIFY_CLIENT_SECRET", ""),
	}

	if cfg.JWTSecret == "" || cfg.JWTSecret == "change-me-in-production" {
		log.Fatal("PANEL_JWT_SECRET is not set to a real secret — refusing to start with a known-insecure default. The installer generates one automatically in panel.env; set it manually if running the binary directly.")
	}
	if cfg.EncryptionKey == "" {
		log.Fatal("PANEL_ENCRYPTION_KEY is not set — refusing to start with a blank encryption key. The installer generates one automatically in panel.env; set it manually if running the binary directly.")
	}

	return cfg
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func parseIntEnv(key string, fallback int) int {
	v := os.Getenv(key)
	if v == "" {
		return fallback
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return fallback
	}
	return n
}

func splitCSV(v string) []string {
	parts := strings.Split(v, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}
